---
title: "Runge-Kutta and ODE Solvers"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = FALSE)
```

## Runge-Kutta 4th order method

Here is the code for the Runge-Kutta 4th order method.  See the lab text book for more information

```{r}
#-------------------------------------------------
#uses the Runge-Kutta 4th order method

#HERE IS OUR MODEL
simple_forest_model <- function(t, states, params){
  
  #"UNPACK" STATES TO THE ACTUAL NAMES
  VEG <- states[1]
  SOIL <- states[2]

  #"UNPACK" params TO THE ACTUAL NAMES
  npp <- params[1]
  mortalityRate <- params[2]
  krate <- params[3]

  #WRITE FLUX EQUATIONS HERE
  VegGrowth <- npp 
  VegMortality <- VEG * mortalityRate
  SoilDecomposition <- SOIL * krate

  #WRITE DERIVATIVES HERE
  dVEG_dt <- VegGrowth - VegMortality
  dSOIL_dt <- VegMortality - SoilDecomposition

  #RETURN A LIST OF THE DERIVATIVES
  return(list(c(dVEG_dt = dVEG_dt,
                dSOIL_dt = dSOIL_dt),
              c(VegGrowth = VegGrowth, 
                VegMortality = VegMortality, 
                SoilDecomposition = SoilDecomposition)))
}

#PARAMETERS
params <- c(
  npp = 300,  #g C m-2 yr-1
  mortalityRate = 0.02, #yr-1
  krate = 0.01) # yr-1

#INITIAL STATES (THE MODEL STARTING POINT)
yini <- c(
  VEG = 1, #g C m-2
  SOIL = 1000) #g C m-2

simulation_time <- 400 #YEARS
dt <- 1
times <- seq(1, simulation_time, by = dt)

nstates <- 2
states <- array(NA,dim = c(length(times), nstates))
states[1, ] <- yini

for(t in 2:length(times)){
  
  #Step 1
  derivatives <- simple_forest_model(times[t], 
                                     states[t - 1, ], params)
  state1_k1 <- derivatives[[1]][1] * dt
  state2_k1  <- derivatives[[1]][2] * dt
  
  #Step 2
  tmp_states <- c(states[t - 1, 1] + state1_k1 / 2, 
                  states[t - 1, 2] + state2_k1 / 2)
  derivatives <- simple_forest_model(times[t] + dt / 2, 
                                     states = tmp_states, params)
  state1_k2 <- derivatives[[1]][1] * dt
  state2_k2  <- derivatives[[1]][2] * dt
  
  #Step 3
  tmp_states <- c(states[t - 1, 1] + state1_k2 / 2, 
                  states[t - 1, 2] + state2_k2 / 2)
  derivatives <- simple_forest_model(times[t] + dt / 2, 
                                     states = tmp_states, params)
  state1_k3 <- derivatives[[1]][1] * dt
  state2_k3  <- derivatives[[1]][2] * dt
  
  #Step 4
  tmp_states <- c(states[t - 1, 1] + state1_k3, 
                  states[t - 1, 2] + state2_k3)
  derivatives <- simple_forest_model(times[t] + dt, 
                                     states = tmp_states, params)
  state1_k4 <- derivatives[[1]][1] * dt
  state2_k4  <- derivatives[[1]][2] * dt
  
  #Combine steps 1 and 4 for State 1 to calculate the
  #state at the next time step
  states[t, 1] <- states[t - 1, 1] + 
    (1 / 6) * state1_k1 + 
    (1 / 3) * state1_k2 + 
    (1 / 3) * state1_k3 + 
    (1 / 6) * state1_k4
  
  #Combine steps 1 and 4 for State 2 to calculate the
  #state at the next time step
  states[t, 2] <- states[t - 1, 2] + 
    (1 / 6) * state2_k1 + 
    (1 / 3) * state2_k2 + 
    (1 / 3) * state2_k3 + 
    (1 / 6) * state2_k4
}


#------------------------------------------------
#Analytical solution

#note: x is time
solved_vegetation_model <- function(x, npp, mortalityRate){
  t <- x
  c <- (1 - (npp / mortalityRate))
  B <- (npp / mortalityRate) + c * exp(-mortalityRate * t)
}

#This is from the model
ylim <- range(c(states[, 1], states[, 2]))
plot(times, states[, 1], type = "l", col = "black", lty = "solid", 
     ylim = ylim, xlab = "time", ylab = "carbon stocks (g C m-2)")
points(times, states[, 2], type = "l", col = "black", lty = "dashed")
legend("bottomright", c("Vegetation", "Soil"), lty = c("solid", "dashed"),
       col = c("black", "black"), bty = "n")

#This adds the analytical solution
curve(solved_vegetation_model(x, npp = 300, mortalityRate = 0.02), 
      from = 1, to = 400, ylim = c(0, 50000), xlab = "time", 
      ylab = "vegetation biomass", col = "gray", lwd = 10, add = TRUE)
points(times, states[, 1], type = "l", col = "black")
legend("topleft", legend = c("Analytical Solution", "Runge-Kutta method"), 
       col = c("gray", "black"), lty = c(1, 1), bty = "n")
```

